
class Device:

    def __init__(self, device_data):

        self.activation_code_expiry_time = device_data['activation_code_expiry_time']
        self.ad_group_id = device_data['ad_group_id']
        self.av_ave_version = device_data['av_ave_version']
        self.av_engine = device_data['av_engine']
        self.av_last_scan_time = device_data['av_last_scan_time']
        self.av_master = device_data['av_master']
        self.av_pack_version = device_data['av_pack_version']
        self.av_product_version = device_data['av_product_version']
        self.av_status = device_data['av_status']
        self.av_update_servers = device_data['av_update_servers']
        self.av_vdf_version = device_data['av_vdf_version']
        self.current_sensor_policy_name = device_data['current_sensor_policy_name']
        self.deregistered_time = device_data['deregistered_time']
        self.device_meta_data_item_list = device_data['device_meta_data_item_list']
        self.device_owner_id = device_data['device_owner_id']
        self.email = device_data['email']
        self.first_name = device_data['first_name']
        self.id = device_data['id']
        self.last_contact_time = device_data['last_contact_time']
        self.last_device_policy_changed_time = device_data['last_device_policy_changed_time']
        self.last_device_policy_requested_time = device_data['last_device_policy_requested_time']
        self.last_external_ip_address = device_data['last_external_ip_address']
        self.last_internal_ip_address = device_data['last_internal_ip_address']
        self.last_location = device_data['last_location']
        self.last_name = device_data['last_name']
        self.last_policy_updated_time = device_data['last_policy_updated_time']
        self.last_reported_time = device_data['last_reported_time']
        self.last_reset_time = device_data['last_reset_time']
        self.last_shutdown_time = device_data['last_shutdown_time']
        self.linux_kernel_version = device_data['linux_kernel_version']
        self.login_user_name = device_data['login_user_name']
        self.mac_address = device_data['mac_address']
        self.middle_name = device_data['middle_name']
        self.name = device_data['name']
        self.organization_id = device_data['organization_id']
        self.organization_name = device_data['organization_name']
        self.os = device_data['os']
        self.os_version = device_data['os_version']
        self.passive_mode = device_data['passive_mode']
        self.policy_id = device_data['policy_id']
        self.policy_name = device_data['policy_name']
        self.policy_override = device_data['policy_override']
        self.quarantined = device_data['quarantined']
        self.registered_time = device_data['registered_time']
        self.scan_last_action_time = device_data['scan_last_action_time']
        self.scan_last_complete_time = device_data['scan_last_complete_time']
        self.scan_status = device_data['scan_status']
        self.sensor_out_of_date = device_data['sensor_out_of_date']
        self.sensor_pending_update = device_data['sensor_pending_update']
        self.sensor_states = device_data['sensor_states']
        self.sensor_version = device_data['sensor_version']
        self.status = device_data['status']
        self.target_priority = device_data['target_priority']
        if device_data["uninstall_code"] is None:
            self.uninstall_code = "Not Found"
        else:
            self.uninstall_code = device_data["uninstall_code"]
        self.vdi_base_device = device_data['vdi_base_device']
        self.virtual_machine = device_data['virtual_machine']
        self.virtualization_provider = device_data['virtualization_provider']
        self.windows_platform = device_data['windows_platform']
